name: Build and deploy Python app to Azure Web App - openmanus0326

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clean up files before deploy
        run: |
          rm -rf .git .github node_modules .venv __pycache__ *.log

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: openmanus0326
          package: .
